/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessTokens: () => import('#controllers/access_tokens_controller'),
  Invitations: () => import('#controllers/invitations_controller'),
  PasswordReset: () => import('#controllers/password_reset_controller'),
  Profile: () => import('#controllers/profile_controller'),
  RefreshTokens: () => import('#controllers/refresh_tokens_controller'),
  shared: {
    RefreshToken: () => import('#controllers/shared/refresh_token'),
  },
}
